### ISSUE TITLE
MSB3322	Unable to get MD5 checksum for the key file "FileTransformerSignKey.pfx".Microsoft.Common.CurrentVersion.targets

### ISSUE THREAD

**Issue by kntjspr** [MichaelYochpaz/FileTransformer#1]
Hello sir I'm currently learning C# encryption and I'm interested on how this tool works. I tried downloading the source but I'm getting an error.
`MSB3322	Unable to get MD5 checksum for the key file "FileTransformerSignKey.pfx".Microsoft.Common.CurrentVersion.targets`

Do I need to do something? It seems like the file doesn't exists. Is there any documentation that or something? Thanks!

IDE: Visual Studio 2021
.NET Framework 5.0

**Comment by MichaelYochpaz** [comment]
Hey, seems like the issue was a few references to `FileTransformerSignKey.pfx` on `FileTransformer.csproj` while the file indeed does not exist.

I wanted to sign the releases back when I released the newer version, but gave up on it and forgot to remove project references.

Anyway, I fixed it now and removed the references, try pulling the latest commit and check if it works for you now.

**Comment by kntjspr** [comment]
Everything's working so far. I'm getting a warning `Warning	MSB3327	Unable to find code signing certificate in the current user’s Windows certificate store. To correct this, either disable signing of the ClickOnce manifest or install the certificate into the certificate store.`

but I haven't found any features that was broken, I guess it's fine.
